working_directory = "dev"

import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"

[window]
blur = true
opacity = 0.8
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
mods = "Option"
key = "b"
chars = "ğŸ›"

[[keyboard.bindings]]
mods = "Option"
key = "c"
chars = "ğŸ¨"

[[keyboard.bindings]]
mods = "Option"
key = "f"
chars = "âœ¨"
