
[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"

[window]
option_as_alt = "OnlyLeft"
dynamic_title = false

[window.padding]
x = 5
y = 5

[[keyboard.bindings]]
mods = "Option"
key = "b"
chars = "ğŸ›"

[[keyboard.bindings]]
mods = "Option"
key = "c"
chars = "ğŸ¨"

[[keyboard.bindings]]
mods = "Option"
key = "f"
chars = "âœ¨"

[general]
working_directory = "dev"

import = ["~/.config/alacritty/catppuccin-mocha.toml"]
